//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSB100UserProfileService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDb
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<int> PersonalIdentityNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string PictureUrl { get; set; }
        public int UserId { get; set; }
    }
}
